#!/bin/bash
set -e

# DOCKER_REPO is like "index.docker.io/foo/bar". The bashism below extracts
# the string after the last "/". For VERSION, we extract the string after the
# first "v" (so v1.2.3 turns into 1.2.3).
NAME=${DOCKER_REPO##*/}
VERSION=${SOURCE_BRANCH#*v}

# If the version is equal to the original value, then we have an invalid
# branch name. In this case, we trigger a Dev build.
if [ "${VERSION}" = "${SOURCE_BRANCH}" ]; then
    echo "=> Building full dev image for branch ${SOURCE_BRANCH}..."
    docker build \
        -t ${IMAGE_NAME} \
        -f $(basename "${BUILD_PATH}") \
        ../..
    exit 0
fi

# We have a NAME and VERSION set, so we build a release image.
echo "=> Building Docker image for ${NAME}:${VERSION}"
docker build \
    -t ${DOCKER_REPO}:${VERSION} \
    -f $(basename "${BUILD_PATH}") \
    --build-arg "NAME=${NAME}" \
    --build-arg "VERSION=${VERSION}" \
    .
