# This dockerfile was not used to build images. It is here as a starting point.
# We will need to use it later when we have build support for windows images.
FROM hashicorppreview/consul-k8s-control-plane:1.0.0-alpha1-windows as windows

COPY "consul-k8s-control-plane.exe" "C:\consul-k8s-control-plane.exe"

# Set Path
RUN SETX /M path "%PATH%;C:\consul-k8s-control-plane.exe;C:\Program Files\Go\bin;"

ENTRYPOINT ["consul-k8s-control-plane.exe"]
