FROM hashicorppreview/consul-k8s-control-plane:1.0.0-alpha1-windows as release-default

COPY "consul-k8s-control-plane.exe" "C:\consul-k8s-control-plane\consul-k8s-control-plane.exe"

ENTRYPOINT ["consul-k8s-control-plane.exe"]
