#!/bin/sh

export CONSUL_K8S_RELEASE_VERSION=1.9.0
export CONSUL_K8S_PRERELEASE_VERSION=rc2
export CONSUL_K8S_PRODUCT_VERSION=1.9.0-rc2
# export CONSUL_K8S_PRODUCT_VERSION=1.9.0
export CONSUL_K8S_RELEASE_BRANCH=release/1.9.0-rc2
# export CONSUL_K8S_RELEASE_BRANCH=release/1.9.x
export CONSUL_K8S_RELEASE_DATE="October 16, 2025"
export CONSUL_K8S_LAST_RELEASE_GIT_TAG="v1.9.0-rc1"
export CONSUL_K8S_CONSUL_DATAPLANE_VERSION=1.9.0-rc2

# NOTE!: This should be the latest Consul **CE** version this release supports.
export CONSUL_K8S_CONSUL_VERSION=1.19.0
