# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# Calico installation for dc3 – IPAM pool 192.170.0.0/16
# Must match the podSubnet in kind-3.config.
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
    - blockSize: 26
      cidr: 192.170.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()

---

apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}
