# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# Calico installation for dc2 – IPv6 IPAM pool fd00:10:245::/64
# Must match the podSubnet in kind-ipv6-2.config.
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
    - blockSize: 122
      cidr: fd00:10:245::/64
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()

---

apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}
