# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

schema = 1
artifacts {
  zip = [
    "consul-cni_${version}+fips1402_linux_amd64.zip",
    "consul-cni_${version}+fips1402_linux_arm64.zip",
    "consul-cni_${version}_linux_386.zip",
    "consul-cni_${version}_linux_amd64.zip",
    "consul-cni_${version}_linux_arm.zip",
    "consul-cni_${version}_linux_arm64.zip",
    "consul-k8s-control-plane_${version}+fips1402_linux_amd64.zip",
    "consul-k8s-control-plane_${version}+fips1402_linux_arm64.zip",
    "consul-k8s-control-plane_${version}+fips1402_windows_amd64.zip",
    "consul-k8s-control-plane_${version}_darwin_amd64.zip",
    "consul-k8s-control-plane_${version}_darwin_arm64.zip",
    "consul-k8s-control-plane_${version}_freebsd_386.zip",
    "consul-k8s-control-plane_${version}_freebsd_amd64.zip",
    "consul-k8s-control-plane_${version}_linux_386.zip",
    "consul-k8s-control-plane_${version}_linux_amd64.zip",
    "consul-k8s-control-plane_${version}_linux_arm.zip",
    "consul-k8s-control-plane_${version}_linux_arm64.zip",
    "consul-k8s-control-plane_${version}_solaris_amd64.zip",
    "consul-k8s-control-plane_${version}_windows_386.zip",
    "consul-k8s-control-plane_${version}_windows_amd64.zip",
    "consul-k8s_${version}+fips1402_linux_amd64.zip",
    "consul-k8s_${version}+fips1402_linux_arm64.zip",
    "consul-k8s_${version}+fips1402_windows_amd64.zip",
    "consul-k8s_${version}_darwin_amd64.zip",
    "consul-k8s_${version}_darwin_arm64.zip",
    "consul-k8s_${version}_freebsd_386.zip",
    "consul-k8s_${version}_freebsd_amd64.zip",
    "consul-k8s_${version}_linux_386.zip",
    "consul-k8s_${version}_linux_amd64.zip",
    "consul-k8s_${version}_linux_arm.zip",
    "consul-k8s_${version}_linux_arm64.zip",
    "consul-k8s_${version}_windows_386.zip",
    "consul-k8s_${version}_windows_amd64.zip",
  ]
  rpm = [
    "consul-cni-${version_linux}-1.aarch64.rpm",
    "consul-cni-${version_linux}-1.x86_64.rpm",
    "consul-cni-fips-${version_linux}+fips1402-1.aarch64.rpm",
    "consul-cni-fips-${version_linux}+fips1402-1.x86_64.rpm",
    "consul-k8s-${version_linux}-1.aarch64.rpm",
    "consul-k8s-${version_linux}-1.x86_64.rpm",
    "consul-k8s-fips-${version_linux}+fips1402-1.aarch64.rpm",
    "consul-k8s-fips-${version_linux}+fips1402-1.x86_64.rpm",
  ]
  deb = [
    "consul-cni-fips_${version_linux}+fips1402-1_amd64.deb",
    "consul-cni-fips_${version_linux}+fips1402-1_arm64.deb",
    "consul-cni_${version_linux}-1_amd64.deb",
    "consul-cni_${version_linux}-1_arm64.deb",
    "consul-k8s-fips_${version_linux}+fips1402-1_amd64.deb",
    "consul-k8s-fips_${version_linux}+fips1402-1_arm64.deb",
    "consul-k8s_${version_linux}-1_amd64.deb",
    "consul-k8s_${version_linux}-1_arm64.deb",
  ]
  container = [
    "consul-k8s_release-default-fips_linux_amd64_${version}+fips1402_${commit_sha}.docker.dev.tar",
    "consul-k8s_release-default-fips_linux_amd64_${version}+fips1402_${commit_sha}.docker.tar",
    "consul-k8s_release-default-fips_linux_arm64_${version}+fips1402_${commit_sha}.docker.dev.tar",
    "consul-k8s_release-default-fips_linux_arm64_${version}+fips1402_${commit_sha}.docker.tar",
    "consul-k8s_release-default_linux_386_${version}_${commit_sha}.docker.dev.tar",
    "consul-k8s_release-default_linux_386_${version}_${commit_sha}.docker.tar",
    "consul-k8s_release-default_linux_amd64_${version}_${commit_sha}.docker.dev.tar",
    "consul-k8s_release-default_linux_amd64_${version}_${commit_sha}.docker.tar",
    "consul-k8s_release-default_linux_arm64_${version}_${commit_sha}.docker.dev.tar",
    "consul-k8s_release-default_linux_arm64_${version}_${commit_sha}.docker.tar",
    "consul-k8s_release-default_linux_arm_${version}_${commit_sha}.docker.dev.tar",
    "consul-k8s_release-default_linux_arm_${version}_${commit_sha}.docker.tar",
    "consul-k8s_ubi-fips_linux_amd64_${version}+fips1402_${commit_sha}.docker.dev.tar",
    "consul-k8s_ubi-fips_linux_amd64_${version}+fips1402_${commit_sha}.docker.redhat.tar",
    "consul-k8s_ubi-fips_linux_amd64_${version}+fips1402_${commit_sha}.docker.tar",
    "consul-k8s_ubi_linux_amd64_${version}_${commit_sha}.docker.dev.tar",
    "consul-k8s_ubi_linux_amd64_${version}_${commit_sha}.docker.redhat.tar",
    "consul-k8s_ubi_linux_amd64_${version}_${commit_sha}.docker.tar",
  ]
}
