# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# This workflow is responsible for validating backports and commenting on backport PRs tagging PR authors to merge in their backport PRs.
# It is scheduled to run at 9:00 AM every day and will also run when manually triggered.

name: Backport Commenter
run-name: Validate backports and notify PRs owners
on:
  push:
    branches:
      - shashank/add-backport-commenter
  schedule:
   - cron: "0 9 * * *"
  workflow_dispatch:
    inputs:
      versions:
        description: "A comma seperated string of the x.y versions representing the backport labels to check. Example: 1.13,1.14,1.15. Defaults to active versions if omitted."
        required: false
        type: string
      begin-date:
        description: "Begin Date to check for PRs being merged. In the format of YYYY-MM-DD. Defaults to the configured begin date if omitted."
        required: false
        type: string

env:
  # This needs to be updated to the date of the last release.
  # workflow_dispatch inputs override these values when manually triggered.
  BPA_COMMENTER_BEGIN_DATE: ${{ github.event.inputs['begin-date'] || '2026-06-05' }}
  # This needs to be updated to the versions that are currently being backported.
  # Active releases: 1.8, 1.9, 2.0
  BPA_COMMENTER_VERSIONS: ${{ github.event.inputs.versions || '1.8.x,1.9.x,2.0.x' }}

jobs:
  validate-backports:
    container: hashicorpdev/backport-assistant:v0.6.3
    runs-on: ubuntu-latest
    steps:
      - name: backport commenter
        env:
          OWNER: hashicorp
          REPO: consul-k8s
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
        run: |
          backport-assistant validate \
            --owner ${OWNER} --repo ${REPO} --versions "${BPA_COMMENTER_VERSIONS}" \
            --begin-date "${BPA_COMMENTER_BEGIN_DATE}" --add-comment